/* Generated By:JJTree: Do not edit this line. ASTIntMultExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTIntMultExpr extends SimpleNode {
  public ASTIntMultExpr(int id) {
    super(id);
  }

  public ASTIntMultExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=313fc9a8aedc72cd51bc77436593a8f7 (do not edit this line) */
