/* Generated By:JJTree: Do not edit this line. ASTTableInversionExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTTableInversionExpression extends SimpleNode {
  public ASTTableInversionExpression(int id) {
    super(id);
  }

  public ASTTableInversionExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cc1bfa432d5722d66a3494d646b3dd54 (do not edit this line) */
