/* Generated By:JJTree: Do not edit this line. ASTTableConcatExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTTableConcatExpr extends SimpleNode {
  public ASTTableConcatExpr(int id) {
    super(id);
  }

  public ASTTableConcatExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=106bf3a343a670733051be46cd21bded (do not edit this line) */
