/* Generated By:JJTree: Do not edit this line. ASTTableRepetitionExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTTableRepetitionExpr extends SimpleNode {
  public ASTTableRepetitionExpr(int id) {
    super(id);
  }

  public ASTTableRepetitionExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=197f18d746cdf5d8811131f287772015 (do not edit this line) */
