/* Generated By:JJTree: Do not edit this line. ASTTableBasicExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTTableBasicExpression extends SimpleNode {
  public ASTTableBasicExpression(int id) {
    super(id);
  }

  public ASTTableBasicExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=944448e76e9b8b120ac87033d428c177 (do not edit this line) */
