/* Generated By:JJTree: Do not edit this line. ASTTableauAssignStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTTableauAssignStmt extends SimpleNode {
  public ASTTableauAssignStmt(int id) {
    super(id);
  }

  public ASTTableauAssignStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3a40e44040175966889b058099bb3a92 (do not edit this line) */
