/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTBLOCK = 1;
  public int JJTSTMT = 2;
  public int JJTASSIGNSTMT = 3;
  public int JJTEXPR = 4;
  public int JJTINTEXPR = 5;
  public int JJTINTADDEXPR = 6;
  public int JJTINTMULTEXPR = 7;
  public int JJTINTNEGEXPR = 8;
  public int JJTINTBASICEXPR = 9;
  public int JJTREALEXPR = 10;
  public int JJTREALADDEXPR = 11;
  public int JJTREALMULTEXPR = 12;
  public int JJTREALNEGEXPR = 13;
  public int JJTREALBASICEXPR = 14;
  public int JJTTABLEEXPR = 15;
  public int JJTTABLECONCATEXPR = 16;
  public int JJTTABLEREPETITIONEXPR = 17;
  public int JJTTABLEINVERSIONEXPRESSION = 18;
  public int JJTTABLEBASICEXPRESSION = 19;
  public int JJTIDENTIFIER = 20;
  public int JJTINTVALUE = 21;
  public int JJTREALVALUE = 22;


  public String[] jjtNodeName = {
    "Program",
    "Block",
    "Stmt",
    "AssignStmt",
    "Expr",
    "IntExpr",
    "IntAddExpr",
    "IntMultExpr",
    "IntNegExpr",
    "IntBasicExpr",
    "RealExpr",
    "RealAddExpr",
    "RealMultExpr",
    "RealNegExpr",
    "RealBasicExpr",
    "TableExpr",
    "TableConcatExpr",
    "TableRepetitionExpr",
    "TableInversionExpression",
    "TableBasicExpression",
    "Identifier",
    "IntValue",
    "RealValue",
  };
}
/* JavaCC - OriginalChecksum=879ebddf28b7f8abb5fd447fcb04fb0f (do not edit this line) */
