/* Generated By:JavaCC: Do not edit this line. ParserDefaultVisitor.java Version 7.0.2 */
package analyzer.ast;

public class ParserDefaultVisitor implements ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntAddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntMultExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntNegExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntBasicExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealAddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealMultExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealNegExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealBasicExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableauAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableConcatExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableRepetitionExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableInversionExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableBasicExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealValue node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=0964954948dc71dd2e91c4ac4f20b38e (do not edit this line) */
