/* Generated By:JJTree: Do not edit this line. ASTArrayAssignStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTArrayAssignStmt extends SimpleNode {
  public ASTArrayAssignStmt(int id) {
    super(id);
  }

  public ASTArrayAssignStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8cf0d09a2e1e9f52e5056e7a847e9571 (do not edit this line) */
