/* Generated By:JJTree: Do not edit this line. ASTArrayBasicExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTArrayBasicExpr extends SimpleNode {
  public ASTArrayBasicExpr(int id) {
    super(id);
  }

  public ASTArrayBasicExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=42322632ccbdd3d4c0385c327c6257a1 (do not edit this line) */
