/* Generated By:JJTree: Do not edit this line. ASTFloatAssignStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTFloatAssignStmt extends SimpleNode {
  public ASTFloatAssignStmt(int id) {
    super(id);
  }

  public ASTFloatAssignStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=233ebc08a9d41195a5b0c9f1427f6e2b (do not edit this line) */
