/* Generated By:JJTree: Do not edit this line. ASTFloatBasicExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTFloatBasicExpr extends SimpleNode {
  public ASTFloatBasicExpr(int id) {
    super(id);
  }

  public ASTFloatBasicExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9a070c6ee48f8d46d21c8174c21683b2 (do not edit this line) */
