/* Generated By:JJTree: Do not edit this line. ASTIntAssignStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTIntAssignStmt extends SimpleNode {
  public ASTIntAssignStmt(int id) {
    super(id);
  }

  public ASTIntAssignStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a4e5f58eb0c1d0de6cd16a8132bceb1 (do not edit this line) */
