/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTBLOCK = 1;
  public int JJTSTMT = 2;
  public int JJTINTASSIGNSTMT = 3;
  public int JJTFLOATASSIGNSTMT = 4;
  public int JJTARRAYASSIGNSTMT = 5;
  public int JJTFORSTMT = 6;
  public int JJTEXPR = 7;
  public int JJTINTADDEXPR = 8;
  public int JJTINTMULTEXPR = 9;
  public int JJTINTUNARYOPEXPR = 10;
  public int JJTINTBASICEXPR = 11;
  public int JJTFLOATADDEXPR = 12;
  public int JJTFLOATMULTEXPR = 13;
  public int JJTFLOATUNARYOPEXPR = 14;
  public int JJTFLOATBASICEXPR = 15;
  public int JJTARRAYCONTEXPR = 16;
  public int JJTARRAYREPEXPR = 17;
  public int JJTARRAYINVEXPR = 18;
  public int JJTARRAYBASICEXPR = 19;
  public int JJTARRAYACCESS = 20;
  public int JJTFCTSTMT = 21;
  public int JJTIDENTIFIER = 22;
  public int JJTINTVALUE = 23;
  public int JJTREALVALUE = 24;
  public int JJTARRAYVALUE = 25;


  public String[] jjtNodeName = {
    "Program",
    "Block",
    "Stmt",
    "IntAssignStmt",
    "FloatAssignStmt",
    "ArrayAssignStmt",
    "ForStmt",
    "Expr",
    "IntAddExpr",
    "IntMultExpr",
    "IntUnaryOpExpr",
    "IntBasicExpr",
    "FloatAddExpr",
    "FloatMultExpr",
    "FloatUnaryOpExpr",
    "FloatBasicExpr",
    "ArrayContExpr",
    "ArrayRepExpr",
    "ArrayInvExpr",
    "ArrayBasicExpr",
    "ArrayAccess",
    "FctStmt",
    "Identifier",
    "IntValue",
    "RealValue",
    "ArrayValue",
  };
}
/* JavaCC - OriginalChecksum=6647ac89cb01f010e12adadbc2c707c0 (do not edit this line) */
