/* Generated By:JavaCC: Do not edit this line. ParserDefaultVisitor.java Version 7.0.2 */
package analyzer.ast;

public class ParserDefaultVisitor implements ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFloatAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArrayAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntAddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntMultExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntUnaryOpExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntBasicExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFloatAddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFloatMultExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFloatUnaryOpExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFloatBasicExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArrayContExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArrayRepExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArrayInvExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArrayBasicExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArrayAccess node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFctStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArrayValue node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=c43a99d8c88ff14584d8c2a749448590 (do not edit this line) */
