/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 7.0.2 */
package analyzer.ast;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTStmt node, Object data);
  public Object visit(ASTIntAssignStmt node, Object data);
  public Object visit(ASTFloatAssignStmt node, Object data);
  public Object visit(ASTArrayAssignStmt node, Object data);
  public Object visit(ASTForStmt node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTIntAddExpr node, Object data);
  public Object visit(ASTIntMultExpr node, Object data);
  public Object visit(ASTIntUnaryOpExpr node, Object data);
  public Object visit(ASTIntBasicExpr node, Object data);
  public Object visit(ASTFloatAddExpr node, Object data);
  public Object visit(ASTFloatMultExpr node, Object data);
  public Object visit(ASTFloatUnaryOpExpr node, Object data);
  public Object visit(ASTFloatBasicExpr node, Object data);
  public Object visit(ASTArrayContExpr node, Object data);
  public Object visit(ASTArrayRepExpr node, Object data);
  public Object visit(ASTArrayInvExpr node, Object data);
  public Object visit(ASTArrayBasicExpr node, Object data);
  public Object visit(ASTArrayAccess node, Object data);
  public Object visit(ASTFctStmt node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntValue node, Object data);
  public Object visit(ASTRealValue node, Object data);
  public Object visit(ASTArrayValue node, Object data);
}
/* JavaCC - OriginalChecksum=c99fc224f30a84993b69e3a03a68f8b1 (do not edit this line) */
