/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package analyzer.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int TYPE = 15;
  /** RegularExpression Id. */
  int STR = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int FLOAT = 18;
  /** RegularExpression Id. */
  int BOOL = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int INPUT = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int REQUAL = 23;
  /** RegularExpression Id. */
  int AEQUAL = 24;
  /** RegularExpression Id. */
  int PLUSEQUAL = 25;
  /** RegularExpression Id. */
  int MINUSEQUAL = 26;
  /** RegularExpression Id. */
  int POWEQUAL = 27;
  /** RegularExpression Id. */
  int DIVEQUAL = 28;
  /** RegularExpression Id. */
  int FOISEQUAL = 29;
  /** RegularExpression Id. */
  int COMPARE = 30;
  /** RegularExpression Id. */
  int LESS = 31;
  /** RegularExpression Id. */
  int LESSEQUAL = 32;
  /** RegularExpression Id. */
  int GREAT = 33;
  /** RegularExpression Id. */
  int GREATEQUAL = 34;
  /** RegularExpression Id. */
  int DIFF = 35;
  /** RegularExpression Id. */
  int EQUALEQUAL = 36;
  /** RegularExpression Id. */
  int AND = 37;
  /** RegularExpression Id. */
  int OR = 38;
  /** RegularExpression Id. */
  int NOT = 39;
  /** RegularExpression Id. */
  int PLUS = 40;
  /** RegularExpression Id. */
  int MINUS = 41;
  /** RegularExpression Id. */
  int TIMES = 42;
  /** RegularExpression Id. */
  int DIV = 43;
  /** RegularExpression Id. */
  int RPLUS = 44;
  /** RegularExpression Id. */
  int RMINUS = 45;
  /** RegularExpression Id. */
  int RTIMES = 46;
  /** RegularExpression Id. */
  int RDIV = 47;
  /** RegularExpression Id. */
  int CONT = 48;
  /** RegularExpression Id. */
  int HASH = 49;
  /** RegularExpression Id. */
  int INV = 50;
  /** RegularExpression Id. */
  int LPAREN = 51;
  /** RegularExpression Id. */
  int RPAREN = 52;
  /** RegularExpression Id. */
  int LACC = 53;
  /** RegularExpression Id. */
  int RACC = 54;
  /** RegularExpression Id. */
  int LCRO = 55;
  /** RegularExpression Id. */
  int RCRO = 56;
  /** RegularExpression Id. */
  int COLON = 57;
  /** RegularExpression Id. */
  int SEMICOLON = 58;
  /** RegularExpression Id. */
  int COMMA = 59;
  /** RegularExpression Id. */
  int IDENTIFIER = 60;
  /** RegularExpression Id. */
  int LETTER = 61;
  /** RegularExpression Id. */
  int DIGIT = 62;
  /** RegularExpression Id. */
  int INTEGER = 63;
  /** RegularExpression Id. */
  int REAL = 64;
  /** RegularExpression Id. */
  int EXPONENT = 65;
  /** RegularExpression Id. */
  int STRING = 66;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"//\"",
    "<token of kind 3>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"in\"",
    "\"do\"",
    "<TYPE>",
    "\"string\"",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"print\"",
    "\"input\"",
    "\"=\"",
    "\"=.\"",
    "\"=*\"",
    "\"+=\"",
    "\"-=\"",
    "\"^=\"",
    "\"/=\"",
    "\"*=\"",
    "<COMPARE>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"not\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"+.\"",
    "\"-.\"",
    "\"*.\"",
    "\"/.\"",
    "\"|\"",
    "\"#\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER>",
    "<REAL>",
    "<EXPONENT>",
    "<STRING>",
  };

}
