package analyzer.ast;/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

import java.util.ArrayList;

public class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }
  public ASTIdentifier(){}
  public ASTIdentifier(ASTIdentifier identifier){
    this.parser = identifier.parser;
    this.id = identifier.id;
    this.children = identifier.children;
    this.parent = identifier.parent;
    this.m_value = identifier.m_value;
  }

  public ASTIdentifier(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public ArrayList<String> reduce(){
    return new ArrayList<String>(){{add(m_value);}};
  }

  // PLB
  private String m_value = null;
  public void setValue(String v) { m_value = v; }
  public String getValue() { return m_value; }
}
