package analyzer.ast;/* Generated By:JJTree: Do not edit this line. ASTIntValue.java */

import java.util.ArrayList;

public class ASTIntValue extends SimpleNode {
  public ASTIntValue(int id) {
    super(id);
  }
  public ASTIntValue(ASTIntValue iVal){super(iVal.getId());}

  public ASTIntValue(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB

  public ArrayList<String> reduce(){
    return new ArrayList<String>(){{add(Integer.toString(m_value));}};
  }
  private int m_value = 0;
  public void setValue(int v) { m_value = v; }
  public int getValue() { return m_value; }
}
