/* Generated By:JJTree: Do not edit this line. ASTIntAddExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

import java.util.Vector;

public
class ASTIntAddExpr extends SimpleNode {
  public ASTIntAddExpr(int id) {
    super(id);
  }

  public ASTIntAddExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }


    // PLB
    private Vector<String> m_ops = new Vector<>();
    public void addOp(String o) { m_ops.add(o); }
    public Vector getOps() { return m_ops; }

}
/* JavaCC - OriginalChecksum=3c4dd6dafdeec8f99732795fff18a9d2 (do not edit this line) */
